import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,ArrowDownToLine,ArrowUpRight,Bookmark,Check,ChevronLeft,ChevronRight,ChevronsLeft,ChevronsRight,Database,Download,FileJson,Filter,LayoutDashboard,List,Pause,Play,Search,Settings,ShieldCheck,Spade,Upload,X,AlertCircle,Radio} from 'lucide-react';
import {bulkExportState,setExcludeBulkExports,recordBulkExport,annotate,annotations,backup,reprocess,initialStatus,listHands,restore,setStatus,status} from '../core/store';
import {demoHands} from '../core/demo';
import {GTO_IMPORT_STATUS,money,type Hand,type Annotation,type RecorderStatus} from '../core/types';
import {validateHand,pokerstars} from '../core/export';
import {replay} from '../core/replay';
import {settlementPots} from '../core/pots';
import './style.css';
import {SingleHandExport} from './SingleHandExport';
import {RecorderNotice,recorderState,recorderLabels} from './RecorderNotice';
const isExtension=typeof chrome!=='undefined'&&!!chrome.runtime?.id;
const labels={recording:'記録中',incomplete:'データ不足',complete:'終了受信'};
const actionLabels={sb:'Small blind',bb:'Big blind',fold:'Fold',check:'Check',call:'Call',bet:'Bet',raise:'Raise',return:'返却'};
const formatDate=(n:number)=>new Date(n).toLocaleString('ja-JP',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
function download(name:string,text:string,type='application/json'){
  const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);
}
function Cards({cards=[],small=false}:{cards?:string[];small?:boolean}){return <span className={`cards ${small?'small':''}`}>{cards.length?cards.map((c,i)=><span key={i} className={`card suit-${c[1]}`}><b>{c[0]==='T'?'10':c[0]}</b><span>{{s:'♠',h:'♥',d:'♦',c:'♣'}[c[1]]??'?'}</span></span>):<span className="unknown-card">—</span>}</span>;}
function App(){
  const [hands,setHands]=useState<Hand[]>([]),[notes,setNotes]=useState<Annotation[]>([]),[rec,setRec]=useState<RecorderStatus>(initialStatus);
  const [tab,setTab]=useState<'hands'|'overview'|'settings'>('hands'),[demo,setDemo]=useState(false),[samples]=useState(demoHands);
  const [selected,setSelected]=useState<string|null>(null),[step,setStep]=useState(0),[query,setQuery]=useState(''),[position,setPosition]=useState('all'),[mode,setMode]=useState('all'),[state,setState]=useState('all'),[onlySaved,setOnlySaved]=useState(false),[from,setFrom]=useState(''),[to,setTo]=useState('');
  const [checked,setChecked]=useState<Set<string>>(new Set),[toast,setToast]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[showExport,setShowExport]=useState(false),[exportReport,setExportReport]=useState(''),[note,setNote]=useState('');
  const [bulkExports,setBulkExports]=useState<{ids:string[];exclude:boolean}>({ids:[],exclude:false});
  const [recLoaded,setRecLoaded]=useState(false);
  const upload=useRef<HTMLInputElement>(null);
  const refresh=async()=>{try{const [h,n,r,b]=await Promise.all([listHands(),annotations(),status(),bulkExportState()]);setBulkExports(b);setHands(h);setNotes(n);setRec(r);setRecLoaded(true);}catch(e){setError(String(e));}};
  useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),3000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(timer);}},[toast]);
  const source=demo?samples:hands;
  const noteMap=useMemo(()=>new Map(notes.map(n=>[n.id,n])),[notes]);
  const filtered=useMemo(()=>source.filter(h=>{
    const hero=h.players.find(p=>p.seat===h.heroSeat);const text=[h.id,h.sourceId,...(hero?.cards??[]),noteMap.get(h.id)?.note].join(' ').toLowerCase();
    return (!query||text.includes(query.toLowerCase()))&&(position==='all'||hero?.position===position)&&(mode==='all'||h.mode===mode)&&(state==='all'||(state==='exportable'?validateHand(h).length===0:h.status===state))&&(!onlySaved||noteMap.get(h.id)?.bookmark)&&(!from||h.startedAt>=new Date(from+'T00:00:00').getTime())&&(!to||h.startedAt<new Date(to+'T00:00:00').getTime()+86400000);
  }).sort((a,b)=>b.startedAt-a.startedAt),[source,query,position,mode,state,onlySaved,noteMap,from,to]);
  const hand=filtered.find(h=>h.id===selected)??filtered[0];
  useEffect(()=>{setStep(hand?.actions.length??0);setNote(hand?noteMap.get(hand.id)?.note??'':'');},[hand?.id]);
  const frame=hand?replay(hand,Math.min(step,hand.actions.length)):null;
  const issues=hand?validateHand(hand):[];
  const pots=hand&&issues.length===0?settlementPots(hand).pots:[];
  const finished=filtered.filter(h=>h.status==='complete'&&h.profit!==null),profit=finished.reduce((n,h)=>n+(h.profit??0),0);
  const ready=filtered.filter(h=>validateHand(h).length===0);
  const selectedHands=checked.size?filtered.filter(h=>checked.has(h.id)):filtered;
  const exportedIds=useMemo(()=>new Set(bulkExports.ids),[bulkExports.ids]);
  const alreadyExported=(h:Hand)=>!demo&&bulkExports.exclude&&exportedIds.has(h.id);
  const eligible=selectedHands.filter(h=>!alreadyExported(h)&&validateHand(h).length===0);
  const skippedExported=selectedHands.filter(alreadyExported).length;
  const receivingState=recorderState(rec);
  const capturing=isExtension&&recLoaded&&receivingState==='receiving';
  const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
  const updateNote=async(bookmark?:boolean)=>{if(!hand)return;if(demo){setToast('デモのメモは保存されません');return;}await annotate({id:hand.id,bookmark:bookmark??noteMap.get(hand.id)?.bookmark??false,note});await refresh();};
  const exportHands=()=>run(async()=>{
    const parts=await Promise.all(eligible.map(pokerstars));if(!parts.length)throw new Error('出力可能なハンドがありません');
    download(`tenfour-${new Date().toISOString().slice(0,10)}${demo?'-DEMO':''}.txt`,parts.join(''),'text/plain');
    if(!demo){
      try{await recordBulkExport(eligible.map(h=>h.id));await refresh();}
      catch{throw new Error('ダウンロードを開始しましたが、出力済みの記録に失敗しました。次回も同じハンドが対象になる可能性があります。');}
    }
    setExportReport(`${parts.length}件のダウンロードを開始しました。${selectedHands.length-parts.length}件は出力済み・データ不足などで除外しました。${GTO_IMPORT_STATUS}`);
  });
  return <div className="app">
    <aside className="sidebar"><a href="#" className="brand" onClick={e=>{e.preventDefault();setTab('hands');}}><span className="brand-icon"><Spade size={24} fill="currentColor"/></span><span>TENFOUR<span className="brand-sub">ANALYZER</span></span></a>
      <div className="workspace-label">YOUR WORKSPACE</div><nav>
        <button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}><LayoutDashboard size={18}/>概要</button>
        <button className={tab==='hands'?'active':''} onClick={()=>setTab('hands')}><List size={18}/>ハンド履歴 <span className="nav-count">{source.length}</span></button>
        <button onClick={()=>{setTab('hands');setOnlySaved(!onlySaved);}} className={onlySaved?'selected':''}><Bookmark size={18}/>ブックマーク</button>
        <button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}><Settings size={18}/>記録・データ管理</button>
      </nav><div className="sidebar-bottom"><div className="private-note"><ShieldCheck size={17}/><div>あなたのデータは、端末内に。<small>クラウドへの送信はありません</small></div></div><div className="version">LOCAL WORKSPACE <span>v0.1.0</span></div></div>
    </aside>
    <main><header className="topbar"><span>Workspace <ChevronRight size={13}/> {tab==='hands'?'ハンド履歴':tab==='overview'?'概要':'記録・データ管理'}</span><div className="top-actions"><button className={`record-indicator ${capturing?'live':''}`} title="記録の受信状況を確認" onClick={()=>setTab('settings')}><i/>{!isExtension?'ブラウザプレビュー':!recLoaded?'記録状況を確認中…':recorderLabels[receivingState]}</button><button className="icon-button" title="データ管理" onClick={()=>setTab('settings')}><Database size={17}/></button></div></header>
      <div className="content">
        {(error||rec.error)&&<div role="alert" className="alert error"><AlertCircle size={18}/>{error||rec.error}<button onClick={()=>{setError('');void setStatus({error:null}).then(refresh);}} aria-label="閉じる"><X size={16}/></button></div>}
        {isExtension&&recLoaded&&!demo&&<RecorderNotice rec={rec} onRefresh={refresh} onResume={()=>run(async()=>{await setStatus({enabled:true});await refresh();})}/>}
        {demo&&<div className="alert demo"><Activity size={17}/>デモモード · 架空のハンドを表示しています。実際の記録とは分離されています。<button onClick={()=>{setDemo(false);setSelected(null);setChecked(new Set);}}>デモを終了 <X size={14}/></button></div>}
        <div className="page-heading"><div><div className="eyebrow">{tab==='settings'?'RECORDER & STORAGE':'YOUR GAME, IN FOCUS'}</div><h1>{tab==='hands'?'ハンド履歴':tab==='overview'?'プレイの振り返り':'記録・データ管理'}</h1><p>{tab==='settings'?'自動記録と、あなたの履歴データを管理します。':'プレイを記録して、気になる一手をじっくり振り返る。'}</p></div><div className="heading-actions">{!demo&&<button className="button secondary" onClick={()=>{setDemo(true);setSelected(null);setChecked(new Set);}}>デモを見る <ArrowUpRight size={15}/></button>}<button className="button primary" disabled={!filtered.length} onClick={()=>{setShowExport(true);setExportReport('');}}><Download size={17}/>エクスポート</button></div></div>
        {tab==='settings'?<section className="settings-grid"><article className="panel settings-card"><Radio size={25}/><h2>自動記録</h2><p>TenFourを開くとゲームの受信データを保存します。拡張導入後はTenFourのページを再読み込みしてください。</p><button className={`button ${rec.enabled?'secondary':'primary'}`} disabled={!isExtension} onClick={()=>void run(async()=>{await setStatus({enabled:!rec.enabled});await refresh();})}>{rec.enabled?<Pause size={16}/>:<Play size={16}/>}記録を{rec.enabled?'停止':'再開'}</button><dl><dt>保存したイベント</dt><dd>{rec.events.toLocaleString()}</dd><dt>最終保存</dt><dd>{rec.lastSaved?formatDate(rec.lastSaved):'まだ記録がありません'}</dd></dl><p className="muted">Chrome / Edgeの拡張機能ページで、配布ZIPを展開したフォルダ（manifest.jsonがある場所）を読み込んで利用します。</p></article>
          <article className="panel settings-card"><Database size={25}/><h2>バックアップと復元</h2><p>原本・ハンド・メモをJSONに保存します。復元は既存データに統合し、同じイベントを重複登録しません。</p><div className="button-row"><button className="button secondary" disabled={busy} onClick={()=>void run(async()=>{download(`tenfour-backup-${Date.now()}.json`,JSON.stringify(await backup()));setToast('バックアップを保存しました');})}><ArrowDownToLine size={16}/>バックアップ</button><button className="button secondary" disabled={busy} onClick={()=>upload.current?.click()}><Upload size={16}/>復元</button></div><p className="muted">ブラウザプレビューと拡張機能の保存領域は別です。拡張機能の削除前にバックアップしてください。</p></article>
          <article className="panel settings-card wide"><Activity size={25}/><h2>受信原本から再処理</h2><p>保存済みの受信データを使ってハンド履歴を再構築します。メモ・ブックマークは保持します。原本が不足するハンドや、受信順序を確定できない旧形式のハンドは更新しません。</p><button className="button secondary" disabled={busy||demo||!rec.events} onClick={()=>void run(async()=>{const report=await reprocess();await refresh();setToast(`${report.rebuiltHands} 件を再構築しました（既存 ${report.preservedHands} 件を維持・順序不明 ${report.ambiguousHands} 件）`);})}><Activity size={16}/>{busy?'処理中…':'原本から再処理'}</button><p className="muted">未取得の通信は補完できません。保存済みの履歴詳細からアクション・精算結果・公開カードを反映します。</p></article>
          <article className="panel settings-card wide"><AlertCircle size={25}/><h2>初期版の対応状況</h2><p>通常・Expert・プライベート卓のSocket.IO受信に対応しています。履歴詳細のJSONも、通常の画面で開いた時に原本として保存します。</p><ul><li>通常卓の実通信で記録・再処理を確認済みです。投入額・精算結果・観測したスタックを照合できたハンドのみ出力します。</li><li>TenFourの履歴詳細を開くと、Fast Fold後のアクション・精算結果・公開カードを補完します。記録との照合に失敗した場合は出力を保留します。</li><li>オールイン・サイドポットは配分を確定できる場合に出力します。Expert・プライベート卓は模擬通信で検証済みで、実卓での確認は未実施です。</li></ul></article></section>:<>
          <div className="stats"><div><span>記録したハンド <List size={15}/></span><strong>{filtered.length.toLocaleString()}<small>hands</small></strong><em>{filtered.length-finished.length} 件は収支集計の対象外</em></div><div><span>受信済みの純収支 <Activity size={15}/></span><strong className={profit>=0?'positive':'negative'}>{profit>0?'+':''}{money(profit)}<small>bb</small></strong><em>終了結果のある {finished.length} 件から集計</em></div><div><span>100ハンドあたり <ArrowUpRight size={15}/></span><strong>{finished.length?money(Math.round(profit/finished.length*100)):'—'}<small>bb / 100</small></strong><em>取得できたハンドのみの参考値</em></div><div><span>出力できるハンド <ShieldCheck size={15}/></span><strong>{ready.length}<small>/ {filtered.length}</small></strong><em>データ整合性の検証を通過</em></div></div>
          {tab==='overview'&&<div className="panel overview"><div><h2>収支の推移</h2><p>終了結果を取得したハンドの累積収支</p></div><ProfitChart hands={finished}/></div>}
          <section className="panel history"><div className="history-toolbar"><h2>すべてのハンド <span>{filtered.length}</span></h2><label className="search"><Search size={16}/><input placeholder="カード・ID・メモで検索" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
            <div className="filters"><Filter size={15}/><label><span className="sr-only">開始日</span><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><span>–</span><label><span className="sr-only">終了日</span><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><select aria-label="ポジション" value={position} onChange={e=>setPosition(e.target.value)}><option value="all">全ポジション</option>{['UTG','HJ','CO','BTN','SB','BB','BTN/SB'].map(p=><option key={p}>{p}</option>)}</select><select aria-label="ゲーム" value={mode} onChange={e=>setMode(e.target.value)}><option value="all">全ゲーム</option><option value="normal">通常</option><option value="expert">Expert</option><option value="private">プライベート</option></select><select aria-label="記録状態" value={state} onChange={e=>setState(e.target.value)}><option value="all">すべての状態</option><option value="complete">終了受信</option><option value="recording">記録中</option><option value="incomplete">データ不足</option><option value="exportable">出力可能</option></select><button className={`filter-bookmark ${onlySaved?'on':''}`} aria-label="ブックマークのみ" onClick={()=>setOnlySaved(!onlySaved)}><Bookmark size={15} fill={onlySaved?'currentColor':'none'}/></button></div>
            {filtered.length?<div className="split"><div className="hand-list"><div className="table-head"><span/><span>ハンド / 日時</span><span>位置</span><span>収支</span></div>{filtered.map(h=>{const hero=h.players.find(p=>p.seat===h.heroSeat);return <div key={h.id} className={`hand-row ${hand?.id===h.id?'chosen':''}`}><input type="checkbox" aria-label={`${h.id}を選択`} checked={checked.has(h.id)} onChange={e=>setChecked(old=>{const n=new Set(old);e.target.checked?n.add(h.id):n.delete(h.id);return n;})}/><button className="row-main" onClick={()=>setSelected(h.id)}><div><Cards cards={hero?.cards} small/>{noteMap.get(h.id)?.bookmark&&<Bookmark size={12} fill="currentColor"/>}</div><small>{formatDate(h.startedAt)} <i className={`dot ${h.status}`}/></small></button><button className="row-position" onClick={()=>setSelected(h.id)}>{hero?.position??'—'}</button><button className={`row-profit ${h.profit===null?'':h.profit>=0?'positive':'negative'}`} onClick={()=>setSelected(h.id)}>{h.profit===null?'—':`${h.profit>0?'+':''}${money(h.profit)}`}<small>bb</small></button></div>})}<div className="list-footer">{filtered.length} hands{checked.size>0&&` · ${checked.size} 件選択中`}</div></div>
              {hand&&frame&&<div className="detail"><div className="detail-heading"><div><span className="eyebrow">HAND REPLAYER</span><h3>{hand.sourceId??hand.tableId}</h3></div><button className={`icon-button ${noteMap.get(hand.id)?.bookmark?'positive':''}`} aria-label="ブックマークを切り替える" onClick={()=>void run(()=>updateNote(!noteMap.get(hand.id)?.bookmark))}><Bookmark size={18} fill={noteMap.get(hand.id)?.bookmark?'currentColor':'none'}/></button></div><div className="detail-meta"><span>{hand.mode==='normal'?'Regular':hand.mode==='expert'?'Expert':'Private'} · {hand.players.length}-max</span><span className={`badge ${hand.status}`}>{hand.historyCompletedAt?'履歴で補完済み':labels[hand.status]}</span><span>{formatDate(hand.startedAt)}</span></div>
                <SingleHandExport key={hand.id} hand={hand}/><div className="poker-table"><div className="felt"><div className="felt-label">TENFOUR <span>REPLAY</span></div><Cards cards={step===hand.actions.length&&hand.status==='complete'?hand.board:frame.board}/><div className="pot">POT <b>{money(frame.pot)} bb</b></div></div>{hand.players.map((p,i)=><div key={p.seat} className={`seat seat-${i} ${p.seat===hand.heroSeat?'hero':''} ${frame.folded.has(p.seat)?'folded':''}`}><span className="seat-position">{p.position}{p.seat===hand.button&&<i>D</i>}</span><span className="seat-name">{p.seat===hand.heroSeat?'You':p.name}</span><b>{frame.balances.get(p.seat)===null?'—':money(frame.balances.get(p.seat)??0)} <small>bb</small></b>{p.seat===hand.heroSeat&&<Cards cards={p.cards} small/>}</div>)}</div>
                <div className="replay-controls"><button aria-label="最初へ" onClick={()=>setStep(0)}><ChevronsLeft size={18}/></button><button aria-label="一手戻る" disabled={step<=0} onClick={()=>setStep(s=>Math.max(0,s-1))}><ChevronLeft size={18}/></button><input aria-label="リプレイの進行" type="range" min="0" max={hand.actions.length} value={Math.min(step,hand.actions.length)} onChange={e=>setStep(Number(e.target.value))}/><button aria-label="一手進む" disabled={step>=hand.actions.length} onClick={()=>setStep(s=>Math.min(hand.actions.length,s+1))}><ChevronRight size={18}/></button><button aria-label="最後へ" onClick={()=>setStep(hand.actions.length)}><ChevronsRight size={18}/></button><span>{Math.min(step,hand.actions.length)} / {hand.actions.length}</span></div>
                <div className="action-title"><h4>アクション</h4><span>投入額は bb 表記</span></div><div className="action-list">{hand.actions.map((a,i)=><button className={`action-row ${i===step-1?'current':''} ${i>=step?'future':''}`} key={i} onClick={()=>setStep(i+1)}><span className="street">{i===0||hand.actions[i-1].street!==a.street?a.street.toUpperCase():''}</span><span className="position-pill">{hand.players.find(p=>p.seat===a.seat)?.position}</span><span className={a.kind==='fold'?'muted':['bet','raise'].includes(a.kind)?'raise-text':''}>{actionLabels[a.kind]}{a.allIn?' · ALL-IN':''}</span><b>{a.amount?`${money(a.kind==='raise'?a.to??a.amount:a.amount)} bb`:''}</b></button>)}</div>
                {hand.status!=='complete'&&<p className="compatibility-note">TenFourの「Hand History」でこのハンドの詳細を開くと、取得した履歴からアクション・精算結果を補完します。</p>}
                {pots.length>1&&<section className="pot-breakdown" aria-label="ポットの内訳"><h4>ポットの内訳</h4>{pots.map((p,i)=><p key={i}><strong>{i===0?'メインポット':`サイドポット ${i}`}</strong> {money(p.amount)} bb · 獲得 {p.awards.map(w=>`${hand.players.find(p=>p.seat===w.seat)?.position}: ${money(w.amount)} bb`).join(' / ')} · レーキ {money(p.rake)} bb</p>)}</section>}
                {(hand.status==='complete'||hand.revealedAt!==undefined)&&<section className="revealed-hands" aria-label="終了後のホールカード"><h4>終了後のホールカード</h4><p className="muted">終了結果で開示されたカードを表示します。</p><div>{hand.players.map(p=><div className="revealed-player" key={p.seat}><span className="position-pill">{p.position}</span><span>{p.seat===hand.heroSeat?'You':p.name}<small>{hand.actions.some(a=>a.seat===p.seat&&a.kind==='fold')?'フォールド':hand.payouts.some(w=>w.seat===p.seat)?'獲得':hand.status==='complete'?'ショーダウン':'履歴で開示'}</small></span>{p.cards.length===2?<Cards cards={p.cards} small/>:<span className="muted">未取得</span>}</div>)}</div></section>}
                {hand.warnings.length>0&&<p className="compatibility-note">{hand.warnings.map(s=>s==='GTOWizardでの取り込み検証は未実施です。'?GTO_IMPORT_STATUS:s).join(' ')}</p>}{issues.length>0&&<details className="issues"><summary><AlertCircle size={14}/>{issues.length} 件の確認事項 · 出力保留</summary><ul>{issues.map(s=><li key={s}>{s}</li>)}</ul></details>}
                {hand.rawLines.length>0&&<details className="raw"><summary>受信したアクション原文</summary><pre>{hand.rawLines.join('\n')}</pre></details>}
                <div className="note"><label htmlFor="hand-note">このハンドのメモ</label><textarea id="hand-note" placeholder="気になった判断、振り返りたいポイント…" value={note} maxLength={10000} onChange={e=>setNote(e.target.value)}/><button className="button small-button secondary" onClick={()=>void run(async()=>{await updateNote();if(!demo)setToast('メモを保存しました');})}>メモを保存</button></div>
              </div>}</div>:<div className="empty"><div className="empty-icon"><Spade size={32}/></div><h2>{source.length?'条件に一致するハンドがありません':'最初のハンドを、ここに。'}</h2><p>{source.length?'検索条件や期間を変更してください。':'拡張機能を有効にしてTenFourをプレイすると、履歴が自動で記録されます。'}</p><div className="button-row"><button className="button primary" onClick={()=>setTab('settings')}>記録の設定を見る <ChevronRight size={15}/></button><button className="button secondary" onClick={()=>setDemo(true)}>デモで使い方を見る</button></div></div>}
          </section><div className="footnote"><ShieldCheck size={13}/>ブラウザ内に保存 · 記録できなかったハンドは集計に含まれません。<span>GTOWizardとの接続・自動送信は行いません</span></div>
        </>}
      </div>
    </main>
    <input ref={upload} type="file" accept="application/json,.json" className="hidden" onChange={e=>{const file=e.target.files?.[0];if(file)void run(async()=>{if(file.size>100_000_000)throw new Error('バックアップは100 MB以下にしてください');const report=await restore(JSON.parse(await file.text()));await refresh();setToast(`ハンド ${report.hands} 件・イベント ${report.events} 件・メモ ${report.annotations} 件を復元しました（既存ハンド ${report.skippedHands} 件を維持）`);});e.target.value='';}}/>
    {toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}
    {showExport&&<div className="modal-overlay" onClick={()=>setShowExport(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="export-title" onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" aria-label="閉じる" onClick={()=>setShowExport(false)}><X size={20}/></button><div className="modal-icon"><FileJson size={28}/></div><h2 id="export-title">ハンドをエクスポート</h2><p>英語のPokerStars互換テキストとして保存します。{demo&&'現在は架空のデモデータです。'}</p>{!demo&&<label className="export-option"><input type="checkbox" checked={bulkExports.exclude} disabled={busy} onChange={e=>{const value=e.currentTarget.checked;setBulkExports(old=>({...old,exclude:value}));void run(async()=>{try{await setExcludeBulkExports(value);}catch(error){await refresh();throw error;}});}}/>一括エクスポート済みのハンドを除外する</label>}<p className="muted">{!demo&&`一括出力済みによる除外：${skippedExported} 件。`}ダウンロード開始時に出力済みとして記録します。保存をキャンセルした場合や再出力したい場合は、除外をオフにしてください。単体出力は出力済みに含めません。{demo&&'デモの出力履歴は保存しません。'}</p><div className="export-count"><strong>{eligible.length}</strong><span>出力可能 / 対象 {selectedHands.length} 件</span></div><p className="muted">{checked.size?'選択したハンド':'現在の絞り込み結果'}が対象です。データ不足のハンドは除外します。{GTO_IMPORT_STATUS}</p>{selectedHands.length>eligible.length&&<details className="issues"><summary>除外されるハンドの理由</summary><ul>{selectedHands.filter(h=>alreadyExported(h)||validateHand(h).length).map(h=><li key={h.id}>{h.sourceId??h.tableId}: {alreadyExported(h)?'一括エクスポート済み':validateHand(h).join(' / ')}</li>)}</ul></details>}<button className="button primary full" disabled={!eligible.length||busy} onClick={()=>void exportHands()}><Download size={17}/>{busy?'作成中…':'.txt をダウンロード'}</button>{exportReport&&<p role="status" className="export-report">{exportReport}</p>}</section></div>}
  </div>;
}
function ProfitChart({hands}:{hands:Hand[]}){const values=[0];for(const h of [...hands].sort((a,b)=>a.startedAt-b.startedAt))values.push(values.at(-1)!+(h.profit??0));const min=Math.min(...values,0),max=Math.max(...values,100),range=max-min||1;const points=values.map((v,i)=>`${30+i/Math.max(1,values.length-1)*900},${170-(v-min)/range*140}`).join(' ');return hands.length?<svg className="chart" viewBox="0 0 960 210" role="img" aria-label={`${hands.length}件のハンドの累積収支`}><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#22856c" stopOpacity=".16"/><stop offset="100%" stopColor="#22856c" stopOpacity="0"/></linearGradient></defs>{[30,100,170].map(y=><line key={y} x1="30" x2="930" y1={y} y2={y} stroke="#e6eae6" strokeDasharray="4 4"/>)}<polygon points={`30,180 ${points} 930,180`} fill="url(#area)"/><polyline points={points} fill="none" stroke="#22856c" strokeWidth="3"/><text x="30" y="202" fill="#7a8580">0 hands</text><text x="850" y="202" fill="#7a8580">{hands.length} hands</text></svg>:<p className="chart-empty">終了したハンドを記録すると、収支の推移を表示します。</p>;}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
