import { chromium } from '@playwright/test';
import { createServer } from 'node:http';
import { readFile, mkdir } from 'node:fs/promises';
import { resolve, extname } from 'node:path';
import assert from 'node:assert/strict';
const root=resolve(process.env.TENFOUR_DIST_DIR??'dist');await mkdir('artifacts',{recursive:true});
const server=createServer(async(req,res)=>{try{const path=resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(path!==root&&!path.startsWith(root+'/'))throw new Error('path');const file=path===root?path+'/index.html':path;const body=await readFile(file);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'})[extname(file)]??'application/octet-stream');res.end(body);}catch{res.statusCode=404;res.end();}});
await new Promise(r=>server.listen(4173,'127.0.0.1',r));
let context;
try{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH,args:['--no-sandbox']});context=await browser.newContext({viewport:{width:1440,height:1050}});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4173/');await page.getByRole('heading',{name:'最初のハンドを、ここに。'}).waitFor();
 await page.getByRole('button',{name:'デモを見る',exact:true}).click();await page.getByRole('heading',{name:'demo-001'}).waitFor();
 await page.screenshot({path:'artifacts/dashboard.png',fullPage:true});
 await page.getByRole('checkbox',{name:'demo:002を選択',exact:true}).check();
 await page.getByRole('button',{name:'このハンドを出力',exact:true}).click();
 const single=page.getByRole('dialog',{name:'このハンドを出力',exact:true});
 const singleText=await single.getByLabel('ハンド履歴テキスト（1件）').inputValue();
 assert.equal((singleText.match(/PokerStars Hand/g)||[]).length,1);assert.match(singleText,/Dealt to Hero \[As Ks\]/);
 await context.grantPermissions(['clipboard-read','clipboard-write']);
 await single.getByRole('button',{name:'テキストをコピー',exact:true}).click();
 assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),singleText);
 const singleDownload=page.waitForEvent('download');await single.getByRole('button',{name:'この1件をダウンロード',exact:true}).click();
 assert.equal(await readFile(await (await singleDownload).path(),'utf8'),singleText);
 await page.evaluate(()=>Object.defineProperty(navigator.clipboard,'writeText',{configurable:true,value:()=>Promise.reject(new Error('denied'))}));
 await single.getByRole('button',{name:'テキストをコピー',exact:true}).click();
 await single.getByRole('alert').filter({hasText:'自動コピーできませんでした'}).waitFor();
 assert.equal(await single.getByLabel('ハンド履歴テキスト（1件）').evaluate(e=>e.selectionEnd-e.selectionStart),singleText.length);
 await page.evaluate(()=>delete navigator.clipboard.writeText);
 await page.keyboard.press('Escape');await single.waitFor({state:'hidden'});
 await page.getByRole('checkbox',{name:'demo:002を選択',exact:true}).uncheck();
 await page.getByPlaceholder('カード・ID・メモで検索').fill('demo-003');
 assert.ok(await page.getByRole('button',{name:'このハンドを出力',exact:true}).isDisabled());
 await page.getByPlaceholder('カード・ID・メモで検索').fill('');

 await page.getByRole('button',{name:'最初へ',exact:true}).click();assert.equal(await page.getByRole('slider').inputValue(),'0');
 await page.getByRole('button',{name:'一手進む',exact:true}).click();assert.equal(await page.getByRole('slider').inputValue(),'1');
 await page.getByRole('button',{name:'最後へ',exact:true}).click();
 await page.getByPlaceholder('カード・ID・メモで検索').fill('Qh');await page.getByRole('heading',{name:'demo-002'}).waitFor();
 await page.getByPlaceholder('カード・ID・メモで検索').fill('');
 await page.getByRole('button',{name:'エクスポート',exact:true}).click();
 const dl=page.waitForEvent('download');await page.getByRole('button',{name:'.txt をダウンロード',exact:true}).click();const download=await dl;const file=await download.path();const text=await readFile(file,'utf8');assert.equal((text.match(/PokerStars Hand/g)||[]).length,2);
 await page.getByRole('dialog').getByRole('button',{name:'閉じる',exact:true}).click();
 await page.getByRole('button',{name:'概要',exact:true}).click();await page.getByRole('heading',{name:'収支の推移'}).waitFor();
 await page.setViewportSize({width:700,height:900});await page.screenshot({path:'artifacts/narrow.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.deepEqual(errors,[]);await browser.close();context=null;
 console.log('PASS: UI navigation, replay, search, txt download, responsive layout; screenshots in artifacts/');
 // Load the real MV3 extension and drive its capture pipeline with synthetic Socket.IO frames.
 context=await chromium.launchPersistentContext('',{channel:'chromium',headless:true,executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH,args:['--no-sandbox',`--disable-extensions-except=${root}`,`--load-extension=${root}`]});
 let worker=context.serviceWorkers()[0];if(!worker)worker=await context.waitForEvent('serviceworker');const extensionId=new URL(worker.url()).host;
 await context.route('https://tenfour-poker.com/**',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><title>Test fixture only</title></head><body><h1>Local test fixture</h1><script>window.socket = new WebSocket("wss://game.tenfour-poker.com/socket.io/?EIO=4&transport=websocket");window.received=[];socket.addEventListener("message",e=>received.push(e.data));</script></body></html>'}));
 let socket;await context.routeWebSocket('wss://game.tenfour-poker.com/**',ws=>{socket=ws;});
 const game=await context.newPage();await game.goto('https://tenfour-poker.com/');
 await game.waitForFunction(()=>window.socket?.readyState===1);
 const state={tableId:'integration-table',buttonPosition:0,mySeatIndex:0,seats:[{playerName:'Hero',uid:'u1',chips:100,cards:['As','Ks']},{playerName:'SB',uid:'u2',chips:99.5},{playerName:'BB',uid:'u3',chips:99}],communityCards:[],isHandInProgress:true,actionHistory:['SB POST 0.5bb','BB POST 1bb'],token:'must-not-persist'};
 const dashboard=await context.newPage();await dashboard.goto(`chrome-extension://${extensionId}/index.html`);
 const notice=dashboard.getByRole('region',{name:'記録の受信状況'});
 await notice.getByRole('heading',{name:'まだ受信を確認できていません',exact:true}).waitFor();
 await notice.getByText('拡張機能の導入・更新後は、TenFourのページを再読み込みしてください。',{exact:true}).waitFor();
 assert.equal(await notice.getByRole('link',{name:'TenFourを開く'}).getAttribute('href'),'https://tenfour-poker.com/');
 await notice.getByRole('button',{name:'状態を更新'}).click();
 await dashboard.setViewportSize({width:390,height:844});
 assert.ok(await dashboard.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await dashboard.screenshot({path:'artifacts/recorder-first-run.png',fullPage:true});
 await dashboard.setViewportSize({width:1280,height:900});
 socket.send('42'+JSON.stringify(['fastFoldTableState',state]));
 await dashboard.getByRole('heading',{name:'table:integration-table',exact:true}).waitFor({timeout:15000});
 await notice.getByRole('heading',{name:'データ受信中',exact:true}).waitFor();
 // Exercise the distinction between a quiet connection, pause and a saving error.
 const patchRecorder=async patch=>{
   await worker.evaluate(async patch=>{
     const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('tenfour-analyzer-v1');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
     try{await new Promise((resolve,reject)=>{const tx=db.transaction('meta','readwrite'),store=tx.objectStore('meta'),r=store.get('status');r.onsuccess=()=>store.put({...r.result,...patch},'status');tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error);});}finally{db.close();}
   },patch);
   await dashboard.reload();
 };
 await patchRecorder({lastSeen:Date.now()-30000});
 await notice.getByRole('heading',{name:'新しいデータを待っています',exact:true}).waitFor();
 await notice.getByText('記録されないときの確認手順',{exact:true}).click();
 await notice.getByRole('button',{name:'状態を更新'}).waitFor();
 await patchRecorder({enabled:false});
 await notice.getByRole('heading',{name:'記録停止中',exact:true}).waitFor();
 assert.equal(await notice.getByRole('link',{name:'TenFourを開く'}).count(),0);
 await notice.getByRole('button',{name:'記録を再開する'}).click();
 await notice.getByRole('heading',{name:'新しいデータを待っています',exact:true}).waitFor();
 await patchRecorder({error:'テスト用保存エラー',lastSeen:Date.now()});
 await notice.getByRole('heading',{name:'保存エラー',exact:true}).waitFor();
 assert.equal(await dashboard.locator('.record-indicator.live').count(),0);
 await patchRecorder({error:null,lastSeen:0});
 await notice.getByRole('heading',{name:'まだ受信を確認できていません',exact:true}).waitFor();
 await patchRecorder({lastSeen:Date.now()});
 await notice.getByRole('heading',{name:'データ受信中',exact:true}).waitFor();
 console.log('PASS: first-run reload instructions, mobile layout, reception, idle help, pause/resume and saving-error status');
 assert.equal(await game.evaluate(()=>received.length),1);
 const raw=await worker.evaluate(async()=>{const req=indexedDB.open('tenfour-analyzer-v1',1);const db=await new Promise((r,j)=>{req.onsuccess=()=>r(req.result);req.onerror=j;});const store=db.transaction('events').objectStore('events');const get=store.getAll();return new Promise((r,j)=>{get.onsuccess=()=>r(JSON.stringify(get.result));get.onerror=j;});});
 assert.ok(!raw.includes('must-not-persist'));assert.ok(raw.includes('integration-table'));
 socket.send('42'+JSON.stringify(['fastFoldTableRemoved',{tableId:'integration-table'}]));
 await dashboard.getByText('卓から退出。終了結果の補完が必要です',{exact:true}).waitFor({state:'attached'});
 await dashboard.screenshot({path:'artifacts/extension-capture.png',fullPage:true});
 await dashboard.reload();await dashboard.getByRole('heading',{name:'table:integration-table',exact:true}).waitFor();
 await dashboard.getByLabel('このハンドのメモ').fill('再処理後も保持');
 await dashboard.getByRole('button',{name:'メモを保存',exact:true}).click();
 await dashboard.getByRole('status').filter({hasText:'メモを保存しました'}).waitFor();
 await dashboard.getByRole('button',{name:'記録・データ管理',exact:true}).click();
 const backupDownload=dashboard.waitForEvent('download');
 await dashboard.getByRole('button',{name:'バックアップ',exact:true}).click();
 const backupFile=await (await backupDownload).path();
 const saved=JSON.parse(await readFile(backupFile,'utf8'));
 await dashboard.locator('input[type="file"]').setInputFiles({name:'restore.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(saved))});
 await dashboard.getByRole('status').filter({hasText:'ハンド 0 件・イベント 0 件・メモ 0 件を復元しました（既存ハンド 1 件を維持）'}).waitFor();
 await dashboard.locator('input[type="file"]').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...saved,hands:[{...saved.hands[0],profit:'bad'}]}))});
 await dashboard.getByRole('alert').filter({hasText:'対応するバックアップ形式ではありません'}).waitFor();
 await dashboard.getByRole('button',{name:'原本から再処理',exact:true}).click();
 await dashboard.getByRole('status').filter({hasText:'1 件を再構築しました（既存 0 件を維持・順序不明 0 件）'}).waitFor();
 await dashboard.getByRole('button',{name:/^ハンド履歴/}).click();
 assert.equal(await dashboard.getByLabel('このハンドのメモ').inputValue(),'再処理後も保持');
 await dashboard.getByText('卓から退出。終了結果の補完が必要です',{exact:true}).waitFor({state:'attached'});
 console.log('PASS: backup download, idempotent restore, invalid backup rejection, reprocessing and note preservation');
 const observed=JSON.parse(await readFile('tests/fixtures/observed-showdown.json','utf8'));
 for(const e of observed.filter(e=>e.event==='fastFoldTableState'))socket.send('42'+JSON.stringify([e.event,e.payload]));
 await dashboard.getByPlaceholder('カード・ID・メモで検索').fill('observed-showdown');
 await dashboard.getByRole('button',{name:'このハンドを出力',exact:true}).waitFor();
 await dashboard.getByRole('button',{name:'このハンドを出力',exact:true}).click();
 const liveText=await dashboard.getByRole('dialog').getByLabel('ハンド履歴テキスト（1件）').inputValue();
 assert.match(liveText,/Hero collected \$4.84/);await dashboard.getByRole('dialog').getByRole('button',{name:'閉じる',exact:true}).click();
 const revealed=dashboard.getByRole('region',{name:'終了後のホールカード'});
 assert.equal(await revealed.locator('.revealed-player').count(),6);
 assert.equal(await revealed.locator('.card').count(),12);
 console.log('PASS: single-hand clipboard and download, clipboard denial fallback, incomplete export guard, observed settlement and all six revealed hands');
 // Single-hand output above must not mark a hand as bulk exported.
 await dashboard.getByRole('button',{name:'エクスポート',exact:true}).click();
 let bulk=dashboard.getByRole('dialog',{name:'ハンドをエクスポート'});
 await bulk.getByLabel('一括エクスポート済みのハンドを除外する').check();
 await bulk.getByRole('button',{name:'.txt をダウンロード',exact:true}).waitFor();
 const bulkDownload=dashboard.waitForEvent('download');
 await bulk.getByRole('button',{name:'.txt をダウンロード',exact:true}).click();
 const bulkText=await readFile(await (await bulkDownload).path(),'utf8');assert.equal((bulkText.match(/PokerStars Hand/g)||[]).length,1);
 await bulk.getByRole('status').filter({hasText:'1件のダウンロードを開始しました。'}).waitFor();
 assert.equal(await bulk.getByRole('button',{name:'.txt をダウンロード',exact:true}).isDisabled(),true);
 await dashboard.reload();
 await dashboard.getByRole('button',{name:'エクスポート',exact:true}).click();
 bulk=dashboard.getByRole('dialog',{name:'ハンドをエクスポート'});
 assert.equal(await bulk.getByLabel('一括エクスポート済みのハンドを除外する').isChecked(),true);
 assert.equal(await bulk.getByRole('button',{name:'.txt をダウンロード',exact:true}).isDisabled(),true);
 await bulk.getByLabel('一括エクスポート済みのハンドを除外する').uncheck();
 await bulk.getByRole('button',{name:'.txt をダウンロード',exact:true}).waitFor();
 await dashboard.waitForFunction(()=>!document.querySelector('.modal [class*=primary]')?.disabled);
 assert.equal(await bulk.getByRole('button',{name:'.txt をダウンロード',exact:true}).isEnabled(),true);
 await bulk.getByRole('button',{name:'閉じる',exact:true}).click();
 console.log('PASS: bulk export excludes previously downloaded hands after reload, single export does not mark, opt-out allows repeat export');

 const folded=JSON.parse(await readFile('tests/fixtures/observed-fast-fold.json','utf8'));
 for(const e of folded.slice(0,2))socket.send('42'+JSON.stringify([e.event,{...e.payload,tableId:'browser-fast-fold'}]));
 socket.send('42'+JSON.stringify(['fastFoldTableRemoved',{tableId:'browser-fast-fold'}]));
 await dashboard.getByPlaceholder('カード・ID・メモで検索').fill('browser-fast-fold');
 await dashboard.getByRole('heading',{name:'table:browser-fast-fold',exact:true}).waitFor();
 assert.ok(await dashboard.getByRole('button',{name:'このハンドを出力',exact:true}).isDisabled());
 const startedAt=await worker.evaluate(async()=>{const db=await new Promise(r=>{const q=indexedDB.open('tenfour-analyzer-v1');q.onsuccess=()=>r(q.result);});return new Promise(r=>{const q=db.transaction('hands').objectStore('hands').get('normal:browser-fast-fold');q.onsuccess=()=>{r(q.result.startedAt);db.close();};});});
 const detail={...folded[2].payload.detail,id:'browser-fast-fold',startedAt:new Date(startedAt).toISOString(),createdAt:new Date().toISOString()};
 await context.route('https://game.tenfour-poker.com/api/hand/browser-fast-fold',r=>r.fulfill({json:detail,headers:{'access-control-allow-origin':'https://tenfour-poker.com'}}));
 await game.evaluate(()=>fetch('https://game.tenfour-poker.com/api/hand/browser-fast-fold').then(r=>r.json()));
 await dashboard.getByText('履歴で補完済み',{exact:true}).waitFor();
 await dashboard.getByRole('button',{name:'このハンドを出力',exact:true}).click();
 assert.match(await dashboard.getByLabel('ハンド履歴テキスト（1件）').inputValue(),/Uncalled bet \(\$2\.00\) returned to Player5/);
 await dashboard.getByRole('dialog').getByRole('button',{name:'閉じる',exact:true}).click();
 await dashboard.getByPlaceholder('カード・ID・メモで検索').fill('');
 await dashboard.getByRole('button',{name:'エクスポート',exact:true}).click();
 bulk=dashboard.getByRole('dialog',{name:'ハンドをエクスポート'});
 await bulk.getByLabel('一括エクスポート済みのハンドを除外する').check();
 const nextDownload=dashboard.waitForEvent('download');
 await bulk.getByRole('button',{name:'.txt をダウンロード',exact:true}).click();
 const nextText=await readFile(await (await nextDownload).path(),'utf8');
 assert.equal((nextText.match(/PokerStars Hand/g)||[]).length,1);
 assert.match(nextText,/Uncalled bet \(\$2\.00\) returned to Player5/);
 assert.doesNotMatch(nextText,/Dealt to Hero \[9d Jh\]/);
 await bulk.getByRole('status').filter({hasText:'1件のダウンロードを開始しました。'}).waitFor();
 await bulk.getByRole('button',{name:'閉じる',exact:true}).click();
 console.log('PASS: next bulk download includes newly completed hand and excludes previous output and incomplete hands');
 // Drive disconnect/reconnect through native WebSocket events and a fresh capture connection.
 socket.send('42'+JSON.stringify(['fastFoldTableState',{...state,tableId:'browser-reconnect'}]));
 await dashboard.getByPlaceholder('カード・ID・メモで検索').fill('browser-reconnect');
 await dashboard.getByRole('heading',{name:'table:browser-reconnect',exact:true}).waitFor();
 socket.close();await dashboard.getByText('接続が終了しました',{exact:true}).waitFor({state:'attached'});
 await game.evaluate(()=>{window.socket=new WebSocket('wss://game.tenfour-poker.com/socket.io/?EIO=4&transport=websocket');});
 await game.waitForFunction(()=>window.socket.readyState===1);
 socket.send('42'+JSON.stringify(['fastFoldTableState',{...state,tableId:'browser-reconnect'}]));
 await dashboard.locator('.badge.recording').waitFor();
 // Stop the MV3 worker, then verify that the next capture wakes it and survives a UI reload.
 const cdp=await context.newCDPSession(dashboard);
 const version=new Promise(resolve=>cdp.on('ServiceWorker.workerVersionUpdated',e=>{const v=e.versions.find(v=>v.scriptURL===`chrome-extension://${extensionId}/background.js`);if(v)resolve(v.versionId);}));
 await cdp.send('ServiceWorker.enable');
 const versionId=await Promise.race([version,new Promise((_,reject)=>setTimeout(()=>reject(new Error('worker version unavailable')),5000))]);
 await cdp.send('ServiceWorker.stopWorker',{versionId});
 socket.send('42'+JSON.stringify(['fastFoldTableState',{...state,tableId:'browser-reconnect',actionHistory:[...state.actionHistory,'BTN RAISE 3bb']} ]));
 await dashboard.getByRole('button').filter({hasText:'Raise'}).waitFor();
 await dashboard.reload();await dashboard.getByPlaceholder('カード・ID・メモで検索').fill('browser-reconnect');
 await dashboard.getByRole('button').filter({hasText:'Raise'}).waitFor();await cdp.detach();
 console.log('PASS: normal HTTP hand-detail capture completes Fast Fold history; WebSocket disconnect/reconnect; MV3 worker restart and persistence');


 console.log('PASS: MV3 injection → WebSocket capture → isolated bridge → service worker → IndexedDB → dashboard, credential filtering, table removal, reload persistence');
}finally{await context?.close();server.close();}
