import { chromium } from '@playwright/test';
import { createServer } from 'node:http';
import { readFile, mkdir } from 'node:fs/promises';
import { resolve, extname } from 'node:path';
import assert from 'node:assert/strict';
const root=resolve('dist');await mkdir('artifacts',{recursive:true});
const server=createServer(async(req,res)=>{try{const path=resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(path!==root&&!path.startsWith(root+'/'))throw new Error('path');const file=path===root?path+'/index.html':path;const body=await readFile(file);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'})[extname(file)]??'application/octet-stream');res.end(body);}catch{res.statusCode=404;res.end();}});
await new Promise(r=>server.listen(4173,'127.0.0.1',r));
let context;
try{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH,args:['--no-sandbox']});context=await browser.newContext({viewport:{width:1440,height:1050}});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4173/');await page.getByRole('heading',{name:'最初のハンドを、ここに。'}).waitFor();
 await page.getByRole('button',{name:'デモを見る',exact:true}).click();await page.getByRole('heading',{name:'demo-001'}).waitFor();
 await page.screenshot({path:'artifacts/dashboard.png',fullPage:true});
 await page.getByRole('button',{name:'最初へ',exact:true}).click();assert.equal(await page.getByRole('slider').inputValue(),'0');
 await page.getByRole('button',{name:'一手進む',exact:true}).click();assert.equal(await page.getByRole('slider').inputValue(),'1');
 await page.getByRole('button',{name:'最後へ',exact:true}).click();
 await page.getByPlaceholder('カード・ID・メモで検索').fill('Qh');await page.getByRole('heading',{name:'demo-002'}).waitFor();
 await page.getByPlaceholder('カード・ID・メモで検索').fill('');
 await page.getByRole('button',{name:'エクスポート',exact:true}).click();
 const dl=page.waitForEvent('download');await page.getByRole('button',{name:'.txt をダウンロード',exact:true}).click();const download=await dl;const file=await download.path();const text=await readFile(file,'utf8');assert.equal((text.match(/PokerStars Hand/g)||[]).length,2);
 await page.getByRole('dialog').getByRole('button',{name:'閉じる',exact:true}).click();
 await page.getByRole('button',{name:'概要',exact:true}).click();await page.getByRole('heading',{name:'収支の推移'}).waitFor();
 await page.setViewportSize({width:700,height:900});await page.screenshot({path:'artifacts/narrow.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.deepEqual(errors,[]);await browser.close();context=null;
 console.log('PASS: UI navigation, replay, search, txt download, responsive layout; screenshots in artifacts/');
 // Load the real MV3 extension and drive its capture pipeline with synthetic Socket.IO frames.
 context=await chromium.launchPersistentContext('',{channel:'chromium',headless:true,executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH,args:['--no-sandbox',`--disable-extensions-except=${root}`,`--load-extension=${root}`]});
 let worker=context.serviceWorkers()[0];if(!worker)worker=await context.waitForEvent('serviceworker');const extensionId=new URL(worker.url()).host;
 await context.route('https://tenfour-poker.com/**',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><title>Test fixture only</title></head><body><h1>Local test fixture</h1><script>window.socket = new WebSocket("wss://game.tenfour-poker.com/socket.io/?EIO=4&transport=websocket");window.received=[];socket.addEventListener("message",e=>received.push(e.data));</script></body></html>'}));
 let socket;await context.routeWebSocket('wss://game.tenfour-poker.com/**',ws=>{socket=ws;});
 const game=await context.newPage();await game.goto('https://tenfour-poker.com/');
 await game.waitForFunction(()=>window.socket?.readyState===1);
 const state={tableId:'integration-table',buttonPosition:0,mySeatIndex:0,seats:[{playerName:'Hero',uid:'u1',chips:100,cards:['As','Ks']},{playerName:'SB',uid:'u2',chips:99.5},{playerName:'BB',uid:'u3',chips:99}],communityCards:[],isHandInProgress:true,actionHistory:['SB POST 0.5bb','BB POST 1bb'],token:'must-not-persist'};
 socket.send('42'+JSON.stringify(['fastFoldTableState',state]));
 const dashboard=await context.newPage();await dashboard.goto(`chrome-extension://${extensionId}/index.html`);
 await dashboard.getByRole('heading',{name:'table:integration-table',exact:true}).waitFor({timeout:15000});
 assert.equal(await game.evaluate(()=>received.length),1);
 const raw=await worker.evaluate(async()=>{const req=indexedDB.open('tenfour-analyzer-v1',1);const db=await new Promise((r,j)=>{req.onsuccess=()=>r(req.result);req.onerror=j;});const store=db.transaction('events').objectStore('events');const get=store.getAll();return new Promise((r,j)=>{get.onsuccess=()=>r(JSON.stringify(get.result));get.onerror=j;});});
 assert.ok(!raw.includes('must-not-persist'));assert.ok(raw.includes('integration-table'));
 socket.send('42'+JSON.stringify(['fastFoldTableRemoved',{tableId:'integration-table'}]));
 await dashboard.getByText('卓から退出。終了結果の補完が必要です',{exact:true}).waitFor({state:'attached'});
 await dashboard.screenshot({path:'artifacts/extension-capture.png',fullPage:true});
 await dashboard.reload();await dashboard.getByRole('heading',{name:'table:integration-table',exact:true}).waitFor();
 await dashboard.getByRole('button',{name:'記録・データ管理',exact:true}).click();
 const backupDownload=dashboard.waitForEvent('download');
 await dashboard.getByRole('button',{name:'バックアップ',exact:true}).click();
 const backupFile=await (await backupDownload).path();
 const saved=JSON.parse(await readFile(backupFile,'utf8'));
 await dashboard.locator('input[type="file"]').setInputFiles({name:'restore.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(saved))});
 await dashboard.getByRole('status').filter({hasText:'ハンド 0 件・イベント 0 件・メモ 0 件を復元しました（既存ハンド 1 件を維持）'}).waitFor();
 await dashboard.locator('input[type="file"]').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...saved,hands:[{...saved.hands[0],profit:'bad'}]}))});
 await dashboard.getByRole('alert').filter({hasText:'対応するバックアップ形式ではありません'}).waitFor();
 console.log('PASS: backup download, idempotent restore report, invalid backup rejection');
 console.log('PASS: MV3 injection → WebSocket capture → isolated bridge → service worker → IndexedDB → dashboard, credential filtering, table removal, reload persistence');
}finally{await context?.close();server.close();}
